### ISSUE TITLE
Cannot Download the file

### ISSUE THREAD

**Issue by Ryu-Nakano** [CiscoDevNet/webex-contact-center-api-samples#155]
**Describe the bug**
Webex CC recording API add the 'Transcription' attribute.
Due to this enhancement, the model does not match the JSON response.
Then, stop extracting.

**Comment by nehawuthoo** [comment]
Code is updated. Please try again and let us know if you still face any diffculties.

**Comment by arubhatt** [comment]
Marking this resolved.
